import { useState } from 'react';
import { CalendarDays, Mail, Phone, Send, Linkedin, Github, MapPin, MessageSquare, Clock3, BriefcaseBusiness } from 'lucide-react';
import { profile } from '../data/portfolioData';
function ContactForm({ mode }) {
    const [state, setState] = useState({ status: 'idle', message: '' });
    const [startedAt] = useState(() => Date.now());
    const submit = async (e) => { e.preventDefault(); const form = e.currentTarget; setState({ status: 'loading', message: 'Sending…' }); try {
        const data = Object.fromEntries(new FormData(form));
        const payload = { ...data, kind: mode, startedAt: Number(data.startedAt), projectType: data.projectType || 'General inquiry' };
        const res = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) });
        if (!res.ok) {
            const j = await res.json().catch(() => ({}));
            throw new Error(j.message || 'Could not send');
        }
        form.reset();
        setState({ status: 'success', message: 'Sent successfully. A confirmation email will also arrive in your inbox.' });
    }
    catch (err) {
        setState({ status: 'error', message: err.message || 'Email delivery needs Gmail/Vercel environment variables configured.' });
    } };
    return <form className="contact-form" onSubmit={submit}><input type="hidden" name="startedAt" value={startedAt}/><input className="trap" name="website" tabIndex="-1" autoComplete="off"/><div className="field-row"><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input name="email" type="email" required placeholder="you@email.com"/></label></div><div className="field-row"><label>Project / conversation type<select name="projectType" defaultValue={mode === 'booking' ? 'Full-stack web app' : 'General inquiry'}><option>Full-stack web app</option><option>React / Next.js product</option><option>SaaS dashboard</option><option>API integration</option><option>Frontend implementation</option><option>Technical mentoring</option><option>General inquiry</option></select></label><label>Company<input name="company" placeholder="Optional"/></label></div>{mode === 'booking' && <><div className="field-row"><label>Budget / context<select name="budget" defaultValue="Need guidance"><option>Need guidance</option><option>$500–$1,000</option><option>$1,000–$3,000</option><option>$3,000+</option><option>Full-time opportunity</option></select></label><label>Phone<input name="phone" placeholder="Optional"/></label></div><div className="field-row"><label>Preferred date<input type="date" name="preferredDate" required/></label><label>Preferred time<input type="time" name="preferredTime" required/></label></div><label>Timezone<input name="timezone" required placeholder="e.g. PKT / UTC+5"/></label></>}<label>Message<textarea name="message" rows="5" minLength="20" required placeholder="Tell me about the goal, scope, timeline or opportunity…"/></label><button className="button button-primary" disabled={state.status === 'loading'}>{mode === 'booking' ? 'Request a Meeting' : 'Send Message'} <Send size={15}/></button>{state.message && <p className={`form-status ${state.status}`}>{state.message}</p>}</form>;
}
export default function ContactBooking() { const [tab, setTab] = useState('contact'); return <section id="contact" className="section shell contact-section"><div className="section-head"><div><span className="section-kicker">GET IN TOUCH</span><h2>Let’s build something <em>worth using.</em></h2></div><p>For opportunities, collaborations, freelance work or mentoring — send the context and I’ll reply by email.</p></div><div className="contact-layout"><aside className="contact-card reveal"><span className="eyebrow-chip">AVAILABLE FOR OPPORTUNITIES</span><h3>Have a project, role or idea in mind?</h3><p>I’m open to full-stack product work, React/Next.js roles, SaaS applications, integrations and selected mentoring collaborations.</p><div className="contact-lines"><a href={profile.gmail} target="_blank" rel="noreferrer"><Mail />{profile.email}</a><a href={`tel:${profile.phone.replace(/\s/g, '')}`}><Phone />{profile.phone}</a><span><MapPin />{profile.location}</span></div><div className="contact-socials"><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin />LinkedIn</a><a href={profile.github} target="_blank" rel="noreferrer"><Github />GitHub</a></div><div className="response-note"><Clock3 /><div><b>Typical response</b><span>Usually within 1–2 business days</span></div></div></aside><div className="contact-workspace reveal"><div className="contact-mode-tabs"><button className={tab === 'contact' ? 'active' : ''} onClick={() => setTab('contact')}><MessageSquare />Send a Message</button><button className={tab === 'booking' ? 'active' : ''} onClick={() => setTab('booking')}><CalendarDays />Book a Meeting</button></div><div className="contact-form-head"><BriefcaseBusiness /><div><small>{tab === 'booking' ? 'PROJECT DISCUSSION' : 'DIRECT MESSAGE'}</small><h3>{tab === 'booking' ? 'Book a focused conversation' : 'Tell me what you are working on'}</h3></div></div><ContactForm mode={tab}/></div></div></section>; }
